// Step 2/5 — create a GitLawb repo owned by the agent DID and push an initial
// README plus a placeholder agent.ts (step 3 overwrites agent.ts with LLM code).

import { createRepo, pushFile } from '../clients/gitlawb.js';
import * as log from '../logger.js';
import type { Config } from '../config.js';
import type { AgentContext, StepResult } from '../types.js';

function readme(did: string): string {
  return `# agent repo

Created autonomously by the 1Claw reference agent.

- **Owner DID:** \`${did}\`
- **Identity:** Ed25519 key held in the 1Claw HSM-backed vault
- **Contents:** an MCP server generated by an LLM via the Shroud TEE proxy (see \`agent.ts\`)

This repository lives on GitLawb — decentralized git over IPFS/libp2p.
`;
}

export async function pushRepo(ctx: AgentContext, config: Config): Promise<StepResult> {
  const shortDid = ctx.did!.slice(-6);
  const name = `agent-${shortDid}`;
  log.detail('did', ctx.did!);
  log.detail('repo', name);

  const { repoUrl } = await createRepo(config, { name, owner: ctx.did! });
  await pushFile(config, { repoUrl, path: 'README.md', content: readme(ctx.did!), message: 'init: agent repo' });
  await pushFile(config, {
    repoUrl,
    path: 'agent.ts',
    content: '// placeholder — replaced by LLM-generated code in step 3\n',
    message: 'chore: stub agent.ts',
  });

  return {
    patch: { repoName: name, repoUrl },
    done: repoUrl,
  };
}
